/*
 * twinder
 * CS6650 assignment API
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.MatchStats;
import io.swagger.client.model.ResponseMsg;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for StatsApi
 */
@Ignore
public class StatsApiTest {

    private final StatsApi api = new StatsApi();

    /**
     * 
     *
     * return number of likes and dislikes for a user
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void matchStatsTest() throws Exception {
        String userID = null;
        MatchStats response = api.matchStats(userID);

        // TODO: test validations
    }
}
