/*
 * twinder
 * CS6650 assignment API
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ResponseMsg;
import io.swagger.client.model.SwipeDetails;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SwipeApi
 */
@Ignore
public class SwipeApiTest {

    private final SwipeApi api = new SwipeApi();

    /**
     * 
     *
     * Swipe left or right
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void swipeTest() throws Exception {
        SwipeDetails body = null;
        String leftorright = null;
        api.swipe(body, leftorright);

        // TODO: test validations
    }
}
